# Generated by Django 5.2 on 2025-05-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={},
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
