# Generated by Django 5.2 on 2025-04-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Mayor', 'Mayor'), ('Vice Mayor', 'Vice Mayor'), ('Councilor', 'Councilor'), ("Mayor's Assistant", "Mayor's Assistant"), ("Vice Mayor's Assistant", "Vice Mayor's Assistant"), ("Councilor's Assistant", "Councilor's Assistant"), ('Security Guard', 'Security Guard')], max_length=30),
        ),
    ]
