# Generated by Django 5.2 on 2025-05-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0002_employee_hourly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='base_salary',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='position',
            name='bonus',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='position',
            name='deduction',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='position',
            name='standard_hours',
            field=models.IntegerField(default=1),
        ),
    ]
