# Generated by Django 5.2 on 2025-05-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0002_alter_attendance_options_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
