# Generated by Django 5.2 on 2025-05-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0004_alter_position_base_salary_alter_position_bonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='standard_hours',
            field=models.IntegerField(),
        ),
    ]
