# Generated by Django 5.2 on 2025-05-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0004_remove_customuser_password_hash_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('mayor', 'Mayor'), ('vice mayor', 'Vice Mayor'), ('councilor', 'Councilor'), ('department head', 'Department Head'), ('clerk', 'Clerk'), ('treasurer', 'treasurer'), ('assessor', 'Assessor'), ('pro', 'Pro'), ('legal officer', 'Legal Officer'), ('hr', 'HR'), ('pm', 'PM'), ('staff', 'Staff'), ('driver', 'Driver'), ('utility', 'Utility')], max_length=30),
        ),
    ]
